--
-- VHDL Test Bench VHDL_PROJECT_lib.debounce_tb.debounce_tester
--
-- Created:
--          by - . (PC-000)
--          at - 01:00:00 01/01/70
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1b (Build 2)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;


ENTITY debounce_tb IS
   GENERIC (
      counter_size : INTEGER := 6
   );
END debounce_tb;


LIBRARY VHDL_PROJECT_lib;
USE VHDL_PROJECT_lib.ALL;


ARCHITECTURE rtl OF debounce_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk    : STD_LOGIC;
   SIGNAL button : STD_LOGIC;
   SIGNAL rst    : STD_LOGIC;
   SIGNAL result : STD_LOGIC;


   -- Component declarations
   COMPONENT debounce
      GENERIC (
         counter_size : INTEGER := 6
      );
      PORT (
         clk    : IN     STD_LOGIC;
         button : IN     STD_LOGIC;
         rst    : IN     STD_LOGIC;
         result : OUT    STD_LOGIC
      );
   END COMPONENT;

   COMPONENT debounce_tester
      GENERIC (
         counter_size : INTEGER := 6
      );
      PORT (
         clk    : OUT    STD_LOGIC;
         button : OUT    STD_LOGIC;
         rst    : OUT    STD_LOGIC;
         result : IN     STD_LOGIC
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : debounce USE ENTITY VHDL_PROJECT_lib.debounce;
   FOR U_1 : debounce_tester USE ENTITY VHDL_PROJECT_lib.debounce_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : debounce
            GENERIC MAP (
               counter_size => counter_size
            )
            PORT MAP (
               clk    => clk,
               button => button,
               rst    => rst,
               result => result
            );

         U_1 : debounce_tester
            GENERIC MAP (
               counter_size => counter_size
            )
            PORT MAP (
               clk    => clk,
               button => button,
               rst    => rst,
               result => result
            );


END rtl;
