--
-- VHDL Test Bench VHDL_PROJECT_lib.Rotary_tb.Rotary_tester
--
-- Created:
--          by - . (PC-000)
--          at - 01:00:00 01/01/70
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1b (Build 2)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ENTITY Rotary_tb IS
END Rotary_tb;


LIBRARY VHDL_PROJECT_lib;
USE VHDL_PROJECT_lib.ALL;


ARCHITECTURE rtl OF Rotary_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL A   : STD_LOGIC;
   SIGNAL B   : STD_LOGIC;
   SIGNAL clk : STD_LOGIC;
   SIGNAL rst : STD_LOGIC;
   SIGNAL P   : STD_LOGIC;
   SIGNAL DIR : STD_LOGIC;


   -- Component declarations
   COMPONENT Rotary
      PORT (
         A   : IN     STD_LOGIC;
         B   : IN     STD_LOGIC;
         clk : IN     STD_LOGIC;
         rst : IN     STD_LOGIC;
         P   : OUT    STD_LOGIC;
         DIR : OUT    STD_LOGIC
      );
   END COMPONENT;

   COMPONENT Rotary_tester
      PORT (
         A   : OUT    STD_LOGIC;
         B   : OUT    STD_LOGIC;
         clk : OUT    STD_LOGIC;
         rst : OUT    STD_LOGIC;
         P   : IN     STD_LOGIC;
         DIR : IN     STD_LOGIC
      );
   END COMPONENT;

   -- embedded configurations
   -- pragma synthesis_off
   FOR U_0 : Rotary USE ENTITY VHDL_PROJECT_lib.Rotary;
   FOR U_1 : Rotary_tester USE ENTITY VHDL_PROJECT_lib.Rotary_tester;
   -- pragma synthesis_on

BEGIN

         U_0 : Rotary
            PORT MAP (
               A   => A,
               B   => B,
               clk => clk,
               rst => rst,
               P   => P,
               DIR => DIR
            );

         U_1 : Rotary_tester
            PORT MAP (
               A   => A,
               B   => B,
               clk => clk,
               rst => rst,
               P   => P,
               DIR => DIR
            );


END rtl;